# Generated by Django 2.2.5 on 2019-09-11 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0002_auto_20190911_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='previous',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_previous', to='elearning.Course'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='previous',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lesson_previous', to='elearning.Lesson'),
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'boolean'), (2, 'one'), (3, 'more_than_one'), (4, 'more_than_one_all')], default=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'student'), (2, 'teacher'), (3, 'admin')], default=1),
        ),
    ]
