  
class USER_TYPE:
  STUDENT = 1
  TEACHER = 2
  ADMIN = 3

class QUESTION_TYPE:
  BOOLEAN = 1
  ONE = 2
  MORE_THAN_ONE = 3
  MORE_THAN_ONE_ALL = 4

class RESPONSE_TYPE:
  SUCCESS = "SUCCESS"
  ERROR = "ERROR"
  WARNING = "WARNING"
  INFO = "INFO"
